### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by xiaywang** [MHersche/eegnet-based-embedded-bci#1]
- You could add explicitly the fix for keras:

change "()" to "[ ]" in line no 1908,1910,1914, 1918 in anaconda3/envs/mybciEnv/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py (e.g. beta = tf.reshape(beta, [-1])) and have 'channels_last' in keras.json

- Remove sentence in models.py talking about channels_first

- get error when saving results "No such file or directory: 'results//stats/global_class_4_ds1_nch64_T3_split_0.csv'". suggestion: use os.path.join(). In save_results in main_global.py {experiment_name} missing: results_str = f'{results_dir}{experiment_name}/stats/global_class_{num_classes}_ds{n_ds}_nch{n_ch}_T{T}_split_{split_ctr}.csv' also line 139 in main_global.py

**Comment by MHersche** [comment]
Thank you for your suggestions. I integrated all of them.

**Comment by MHersche** [comment]
Thank you for your suggestions. I integrated all of them.

**Comment by MHersche** [comment]
Thank you for your suggestions. I integrated all of them.

**Comment by MHersche** [comment]
Thank you for your suggestions. I integrated all of them.

**Comment by MHersche** [comment]
Thank you for your suggestions. I integrated all of them.
